//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int MaintenanceID { get; set; }
        public string ProductSKU { get; set; }
        public string Strategy { get; set; }
        public System.DateTime InitialDate { get; set; }
        public int Interval { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
