//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductSKU { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }

        public override string ToString()
        {
            return String.Format("{0} {1, 30} {2, 8:C2}", ProductSKU, ProductName, Price);
        }
    }

}
