//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Total { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
