//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeafoliaInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public string MaintenanceID { get; set; }
        public string ProductSKU { get; set; }
        public string Strategy { get; set; }
        public System.DateTime InitialDate { get; set; }
        public int Interval { get; set; }

        public override string ToString()
        {
            return String.Format("{0}\n{1}\n{2} - Interval of {3} days", ProductSKU, Strategy, InitialDate.ToString(), Interval);
        }
    }
}
